---
name: Update flake inputs

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  flake-update:
    runs-on: ubuntu-24.04
    if: vars.APP_ID
    strategy:
      matrix:
        branch: [master, release-25.05]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - uses: DeterminateSystems/nix-installer-action@v17

      - id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: DeterminateSystems/update-flake-lock@v25
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update_flake_lock_action_${{ matrix.branch }}
          commit-msg: "flake: update all inputs"
          pr-title: "${{ startsWith(matrix.branch, 'release') && format('[{0}] ', matrix.branch) || '' }}stylix: update all flake inputs"   # yamllint disable-line rule:line-length
          pr-labels: "topic: dependencies"
          pr-body: >
            Automated changes by the
            [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock)
            GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
